Iter13
KznRkjp/go-link-shortner pull request #14
Opened 2024-05-19 18:23 UTC by KznRkjp

2024-05-20 07:21 UTC, edylcrm requested changes

2024-05-20 07:21 UTC, edylcrm commented on internal/app/app.go
> +			log.Fatal(err)
log.Fatal принудительно завершит приложение аналогично панике, точно ли нужно это делать если не получится создать Producer или записать в него event?

2024-05-20 07:21 UTC, edylcrm commented on internal/database/database.go
> +		panic(err)
Опять же давай здесь уберем использование panic, если по какой-то причине не удалось подключиться к БД для одного из большого количества запросов это не значит что приложение нужно завершать в аварийном режиме. И я бы подключался к БД один раз при старте приложения и использовать это подключение везде

2024-05-20 07:21 UTC, edylcrm commented on internal/database/database.go
> +		panic(err)
Тоже самое про панику

2024-05-20 07:21 UTC, edylcrm commented on internal/database/database.go
> +		_, err = conn.Exec(insertDynStmt, url, originalURL, nil)
Здесь лучше использовать методы которые первым аргументом принимают context. Для каждого клиентского запроса создается свой context получить его можно из request. Если по какой-то причине клиент закрыл подключение не дождавшись ответа, то запрос в БД уже делать не нужно. Context в этом случае изменит свое состояние на завешенный, драйвер к БД проверит это и не будет делать запрос, что позволит снизить кол-во запросов в БД

2024-05-20 07:21 UTC, edylcrm commented on internal/database/database.go
> +		_, err := tx.ExecContext(ctx,
Тоже самое про context

2024-05-20 07:21 UTC, edylcrm commented on internal/database/database.go
> +	insertDynStmt := `SELECT originalurl FROM url where shorturl = '` + shortURL + `'`
Тоже самое про context

2024-05-20 07:21 UTC, edylcrm commented on internal/database/database.go
> +		insertDynStmt := `SELECT shorturl FROM url where originalurl = '` + URL + `'`
Тоже самое про context

2024-05-21 07:51 UTC, KznRkjp commented on internal/app/app.go
> +			log.Fatal(err)
так? )

2024-05-21 07:53 UTC, KznRkjp commented on internal/database/database.go
> +		panic(err)
поменял

2024-05-21 07:56 UTC, KznRkjp commented on internal/database/database.go
> +		panic(err)
done

2024-05-21 08:22 UTC, KznRkjp commented on internal/database/database.go
> +	insertDynStmt := `SELECT originalurl FROM url where shorturl = '` + shortURL + `'`
+

2024-05-21 08:22 UTC, KznRkjp commented on internal/database/database.go
> +		insertDynStmt := `SELECT shorturl FROM url where originalurl = '` + URL + `'`
+

2024-05-22 08:09 UTC, edylcrm approved these changes

2024-05-22 13:36 UTC, merged