Iter15
KznRkjp/go-link-shortner pull request #16
Opened 2024-06-03 14:32 UTC by KznRkjp

2024-06-07 10:03 UTC, edylcrm requested changes

2024-06-07 10:03 UTC, edylcrm commented on internal/database/database.go
> +	conn, err := sql.Open("pgx", flags.FlagDBString)
Я бы здесь предложил сделать структуру и прокидывать ей db connect как зависимость, чтобы каждый раз не делать новое подключение. На большом кол-ве трафика это может приводить к деградациям. 
```
type Storage struct {
    db *sqlx.DB
}

func NewStorage(*sqlx.DB) *Storage {
    return &Storage{db: db}
}

func (s *Storage) GetUser(ctx context.Context, uuid string) (int, error) {
    // ...
    s.db.QueryRowContext(...)
    // ...
 }
 ```
 Что-то вроде такого

2024-06-07 10:03 UTC, edylcrm commented on internal/database/database.go
> +		panic(err)
Давай уберем панику. Паника аварийно завершаем приложение. Кажется, что если из 1т запросов по какой-то причине один будет ошибочный это не повод завершать приложение. Достаточно сказать пользователю что возникла какая-то ошибка

2024-06-09 15:04 UTC, KznRkjp commented on internal/database/database.go
> +		panic(err)
+

2024-06-09 15:47 UTC, KznRkjp commented on internal/database/database.go
> +	conn, err := sql.Open("pgx", flags.FlagDBString)
сделал немного по другому

2024-06-09 16:03 UTC, KznRkjp commented on internal/database/database.go
> +		panic(err)
+

2024-06-10 07:36 UTC, edylcrm approved these changes

2024-06-12 08:26 UTC, merged